### PR TITLE
Add iOS and typings support

### PR DESCRIPTION
**Pull request by hypery2k**
- Use correct Pod config
- Adding typings file
- Basic Travis CI config

### CODE REVIEW

**Comment by hypery2k** [comment]
For Travis CI you need to activate it at https://travis-ci.org. Just log in with your Github account and activate it for this repo

**Comment by TobiasHennig** [comment]
Thank you so much @hypery2k for all the work and your time. My time is short and i was hoping someone helps with the ios part. I've activated the repo on travis-ci and try to run your setup on my machine now.

**Comment by TobiasHennig** [comment]
Are you interested in being an collaborator for this repo?

**Comment by hypery2k** [comment]
yes sure. feel free to add me

**Pull request merged**
