### PR TITLE
use Toaster 2.1.1 that supports Swift4

### PR DESCRIPTION
**Pull request by championswimmer**

### CODE REVIEW

**Comment by championswimmer** [comment]
fixes https://github.com/TobiasHennig/nativescript-toast/issues/34

**Comment by farfromrefug** [comment]
@hypery2k could you please merge and release this?

**Comment by hypery2k** [comment]
I merged, but CI build doesn't work, tried to fix it, but wasn't able to fix it within 3 hours - so have to postpone it

**Comment by farfromrefug** [comment]
@hypery2k can i help in any way? Can we see the CI error log?

**Comment by hypery2k** [comment]
you can try this branch: https://github.com/TobiasHennig/nativescript-toast/tree/bugfix/ci_build 
If it's getting through in travis that would help

**Comment by seaware** [comment]
Is there a solution for this? I upgraded to the latest v5 NativeScript and now get `warning: Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "Toaster" to Swift 4.2 using "Convert > To Current Swift Syntax…" in the Edit menu. (in target 'Toaster')`. FYI NativeScript installed Toaster v2.0.4 even though I explicitly asked for 2.1.1 as a dependency.

**Comment by hypery2k** [comment]
as long as it‘s just a warning no problem. But for Swift 4+ compatiblity create a new issue.

But right now Toaster doesn’t support Swift 4, see 
https://github.com/devxoul/Toaster/issues/139

**Pull request merged**
